package:
  name: processflow
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/E3SM-Project/processflow.git
  git_tag: {{ environ['TAG'] }}

build:
  script: python setup.py install
  string: {{ environ['BUILD_NAME'] }}

about:
    home: https://github.com/ACME-Climate/acme_workflow
    summary: Automated post processing for E3SM model data

requirements:
  build:
    - python
    - setuptools
  
  run:
    - pip
    - python
    - setuptools
    - nco
    - ncl
    - acme_diags
    - sqlite
    - peewee
    - configobj
    - beautifulsoup4
    - lxml
    - paramiko
    - jinja2
    - globus-sdk ==1.1.1
    - globus-cli ==1.1.2
    - click
    - jmespath
    - requests
