package:
  name: acme_automated
  version: "0.1"

source:
  git_rev: "0.1"
  git_url: https://github.com/sterlingbaldwin/acme_workflow.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - backports=1.0
    - backports_abc=0.5 
    - basemap=1.0.7
    - bleach=1.5.0 
    - bokeh=0.12.5 
    - bottleneck=1.0.0
    - cairo=1.14.8
    - chest=0.2.3 
    - cloog=0.18.0
    - cloudpickle=0.2.2 
    - cdat_info=2.8 
    - cffi=1.7.0 
    - distarray=2.8 
    - enum34=1.1.6
    - ffmpeg=2.8.6
    - g2clib=1.6.0
    - gmp=6.1.2
    - gsl=2.2.1
    - hdf4=4.2.12
    - hdf5=1.8.17
    - idna=2.1 
    - ipaddress=1.0.16 
    - krb5=1.14.2
    - libcdms=2.8
    - libcf=1.0 
    - libdrs=2.8
    - libnetcdf=4.4.1.1
    - libpng=1.6.28
    - libtiff=4.0.6
    - mpc=1.0.3=4
    - mpfr=3.1.5=0
    - nco=4.6.5=0
    - netcdf-fortran=4.4.4
    - netcdf4=1.2.7
    - proj4=4.9.3
    - pyasn1=0.2.3 
    - pycparser=2.17 
    - pyopenssl=16.2.0 
    - requests=2.13.0 
    - x264=20131217
    - xz=5.2.2
    - configparser=3.5.0 
    - cryptography=1.7.1 
    - curl=7.45.0
    - cycler=0.10.0 
    - dask=0.13.0 
    - dbus=1.10.10
    - decorator=4.0.11 
    - entrypoints=0.2.2
    - expat=2.1.0
    - fontconfig=2.12.1
    - freetype=2.5.5
    - funcsigs=1.0.2 
    - functools32=3.2.3.2 
    - futures=3.0.5 
    - gcc=4.8.5
    - geos=3.3.3
    - get_terminal_size=1.0.0 
    - glib=2.50.2
    - harfbuzz=0.9.39
    - heapdict=1.0.0
    - html5lib=0.999 
    - icu=54.1
    - ipykernel=4.6.0 
    - ipython=5.3.0 
    - ipython_genutils=0.2.0 
    - isl=0.12.2
    - jinja2=2.9.6 
    - jpeg=9b
    - jsonschema=2.5.1 
    - jupyter_client=5.0.1 
    - jupyter_core=4.3.0 
    - libffi=3.2.1
    - libgcc=5.2.0
    - libgfortran=3.0.0
    - libiconv=1.14
    - libsodium=1.0.10
    - libxcb=1.12
    - libxml2=2.9.4
    - libxslt=1.1.29
    - locket=0.2.0
    - lxml=3.7.3 
    - markupsafe=0.23
    - matplotlib=1.5.1
    - mistune=0.7.4 
    - mkl=11.3.3
    - mock=2.0.0 
    - mpmath=0.19
    - nbconvert=5.1.1 
    - nbformat=4.3.0 
    - nose=1.3.7
    - notebook=5.0.0 
    - numexpr=2.6.0
    - numpy=1.10.4
    - opengeostat::pyevtk=1.0.0 
    - openssl=1.0.2k
    - pandas=0.18.1
    - pandocfilters=1.4.1 
    - pango=1.40.3=1
    - partd=0.3.7 
    - path.py=10.1 
    - pathlib2=2.2.0 
    - pbr=1.10.0 
    - pcre=8.39=1
    - pexpect=4.2.1 
    - pickleshare=0.7.4 
    - pillow=4.1.0 
    - pip=9.0.1
    - pixman=0.34.0
    - progressbar=2.3 
    - prompt_toolkit=1.0.14
    - ptyprocess=0.5.1 
    - pycairo=1.10.0 
    - pygments=2.2.0 
    - pyparsing=2.1.4 
    - pyproj=1.9.5.1 
    - pyqt=4.11.4
    - python=2.7.13
    - python-dateutil=2.6.0 
    - pytz=2016.10 
    - pyyaml=3.12 
    - pyzmq=16.0.2 
    - qt=4.8.7=4
    - readline=6.2
    - scandir=1.5 
    - scipy=0.17.1
    - cartopy=0.15.0
    - olefile=0.42.1
    - owslib=0.10.3 
    - proj.4=4.9.1
    - pyepsg=0.2.0 
    - pyshp=1.2.3 
    - setuptools=27.2.0 
    - shapely=1.5.16 
    - simplegeneric=0.8.1
    - singledispatch=3.4.0.3 
    - sip=4.18 
    - six=1.10.0 
    - sqlite=3.13.0
    - ssl_match_hostname=3.4.0.2
    - sympy=1.0 
    - terminado=0.6 
    - testpath=0.3 
    - tk=8.5.18
    - toolz=0.8.2 
    - tornado=4.4.2 
    - traitlets=4.3.2 
    - mesalib=7.6.1
    - cdms2=2017.03.01
    - cdtime=2.8
    - cdutil=2.8
    - clapack=3.2.1
    - dv3d-nox=2.8
    - esmf=ESMF_6_3_0rp1_ESMP_01
    - eztemplate-nox=2.8
    - genutil=2.8
    - jasper=1.900.1
    - lapack=3.4.2
    - libdrs_f=1.0.1
    - ossuuid=1.6.2
    - output_viewer=1.2.2 
    - udunits2=2.2.17
    - unidata=2.8
    - uvcmetrics-nox=2.2
    - vcs-nox=2.8
    - vcsaddons-nox=2.8
    - vtk-cdat-nox=7.1.0.2.8
    - vtk=6.3.0=py27_1
    - wcwidth=0.1.7 
    - wheel=0.29.0 
    - xarray=0.9.2 
    - yaml=0.1.6=0
    - zeromq=4.1.5=0
    - zlib=1.2.8=3
test:
  imports:
    -

about:
  home: https://github.com/sterlingbaldwin/acme_workflow
  license: BSD
  license_file: https://opensource.org/licenses/BSD-3-Clause
